name: Abeln8rs Plugin
main: com.abeln8r.Abeln8rsPlugins.Abeln8rsPlugins
version: 2
softdepend: []
commands:
   tk:
      description: Allows you to talk as another player.
      usage: |
           /<command> <playername> <message>
   vis:
      description: Allows you to hide or show yourself and check your visibility status.
      usage: |
           /<command> <hide:show:status>
   ecry:
      description: Allows you to spawn an Ender Crystal under you.
      usage: |
           /<command> 