name: Abeln8rs Plugin
main: com.abeln8r.Abeln8rsPlugins.Abeln8rsPlugins
version: 2
softdepend: []
commands:
   tk:
      description: allows you to talk as another player.
      usage: |
           /<command> <playername> <message>